#!/usr/bin/env python3
"""Refresh the "Browse the crates" cover pools from shop.vinylsharp.com.

Downloads 16 in-stock covers per tile into assets/img/crates/<tile>/NN.jpg
(300x300, self-hosted) and writes assets/js/crates-data.js, which main.js
rotates through every 2 days. Run whenever you want a fresh pool:

    python3 tools/refresh-crates.py

Needs: Pillow (pip install pillow). Not required for deploying the site.
"""
import json, os, io, urllib.request
from PIL import Image

BASE = "https://shop.vinylsharp.com"
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
POOL = 16
TILES = {
    "new-arrivals": ["records/new-arrivals?limit=60&page=1", "records/new-arrivals?limit=60&page=2"],
    "rock":         ["records?genre=Rock&sortBy=popularity&limit=60"],
    "jazz-blues":   ["records?genre=Jazz&sortBy=popularity&limit=40", "records?genre=Blues&sortBy=popularity&limit=40"],
    "pop-soul":     ["records?genre=Pop&sortBy=popularity&limit=40", "records?genre=Soul&sortBy=popularity&limit=40"],
}

def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=30).read()

def candidates(paths):
    lists = [json.loads(get(f"{BASE}/api/v1/{p}"))["data"] for p in paths]
    out, i = [], 0
    while any(i < len(l) for l in lists):          # interleave so mixed tiles stay mixed
        for l in lists:
            if i < len(l):
                r = l[i]
                if r.get("inStock") and r.get("primaryImage"):
                    out.append(r)
        i += 1
    return out

manifest, seen = {}, set()
for tile, paths in TILES.items():
    folder = os.path.join(ROOT, "assets", "img", "crates", tile)
    os.makedirs(folder, exist_ok=True)
    for f in os.listdir(folder):
        os.remove(os.path.join(folder, f))
    files = []
    for r in candidates(paths):
        if len(files) >= POOL:
            break
        key = (r["title"].lower(), r["artist"].lower())
        if key in seen:
            continue
        try:
            img = Image.open(io.BytesIO(get(BASE + r["primaryImage"]))).convert("RGB")
        except Exception:
            continue
        w, h = img.size
        s = min(w, h)
        img = img.crop(((w - s) // 2, (h - s) // 2, (w + s) // 2, (h + s) // 2)).resize((300, 300))
        name = f"{len(files)+1:02d}.jpg"
        img.save(os.path.join(folder, name), quality=82, optimize=True)
        files.append(f"assets/img/crates/{tile}/{name}")
        seen.add(key)
        print(tile, name, r["title"], "-", r["artist"])
    manifest[tile] = files

with open(os.path.join(ROOT, "assets", "js", "crates-data.js"), "w") as fh:
    fh.write("/* Generated by tools/refresh-crates.py — do not edit by hand. */\n")
    fh.write("window.VS_CRATES = " + json.dumps(manifest, indent=2) + ";\n")
print("done")
